// MUTATIONS TYPES

// Main

export const SET_IS_ONLINE = 'SET_IS_ONLINE'

// Messages

export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const TOGGLE_MESSAGE = 'TOGGLE_MESSAGE'
export const TOGGLE_ALL_MESSAGES = 'TOGGLE_ALL_MESSAGES'
